.load_sqlite: &load_sqlite |
  cd /u01/app/django/orafun/
  sudo python3 manage.py shell << EOF
  import load_data
  load_data.load_fun("functions.csv")
  exit()
  EOF

copy_functions:
  script: 
    - sed -i 1i"name|description" functions.csv
    - sudo cp functions.csv /u01/app/django/orafun/ 
    - *load_sqlite
  tags:
    - orafun1

functions_csv:
  script:
    - [ -d /tmp/gitlab-runner ] \|\| mkdir /tmp/gitlab-runner
    - cp functions.csv /tmp/gitlab-runner/functions.csv
    - export ORACLE_HOME=/opt/oracle/product/18c/dbhomeXE; echo "whenever sqlerror exit failure; exec load_csv_functions; exit" \| $ORACLE_HOME/bin/sqlplus orafun_loader/orafun_loader@//localhost/xepdb1
  tags:
    - orafun2
