.load_sqlite: &load_sqlite |
  cd /u01/app/django/orafun/
  sudo python3 manage.py shell << EOF
  import load_data
  load_data.load_fun("functions.csv")
  exit()
  EOF

copy_functions:
  script: 
    - sed -i 1i"name|description" functions.csv
    - sudo cp functions.csv /u01/app/django/orafun/ 
    - *load_sqlite
  tags:
    - orafun1
